### ISSUE TITLE
how does the data-harmonization project relate to CampFHIR?

### ISSUE THREAD

**Issue by mellybelly** [data2health/data-harmonization#2]
@empfff

**Comment by empfff** [comment]
Last I heard, Ken Gersing was going to see if the application would be useful for the FDA project. While we wait to hear back about that, our next goal is to map i2b2 ACT ontology through CAMP FHIR. Ken gave us some materials to start with, but there's quite a bit of mapping for us to do. We are also open to switching gears and mapping something else if it would better serve the big picture.
