### ISSUE TITLE
Reach out to community members that expressed interest

### ISSUE THREAD

**Issue by jmcmurry** [data2health/data-harmonization#3]
If you haven't already, please make sure to reach out to the PIs that already expressed interest in the project. Select your project from the dropdown [here](https://docs.google.com/spreadsheets/d/1PR6jLSz3KedD9bEWQcFr-LJRQfkXo_GcFOHXZMOgd7o/edit#gid=0).

**Comment by jmcmurry** [comment]
ps. This just in: a coordinated email will be going out for all projects; stay tuned.

**Comment by jmcmurry** [comment]
Baseline email was sent; all ok to proceed with project - specific communications.

**Comment by cgchute** [comment]
Many thanks!
